[smithery]
name = "MCP-DayOne"
version = "2.0.0"
description = "MCP server for Day One Journal integration with Claude Desktop"
author = "Kevin Davison"
license = "MIT"

[install]
dependencies = [
    "python >= 3.11",
    "uv",
    "dayone2"
]

[install.steps]
1 = "uv sync"

[run]
command = "uv run python -m mcp_dayone.server"

[test]
command = "uv run python test_setup.py"

[documentation]
homepage = "https://github.com/Quevin/mcp-dayone"

